version: "3"
services: 
  paradigmi-playground:
    build: . 
    # image: paradigmi/paradigmi
    ports:
      - 8888:8888
    volumes:
      - ./../notebooks:/mnt/paradigmi
    privileged: true
    mem_limit: 512m   # opzionale
